name: EspoCRM Pipeline Execution Test Final Module

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, reopened, synchronize ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install requests
          pip install jsonschema
          pip install pytest-html
          pip install allure-pytest 

      - name: Run tests and generate allure results
        run: |
          pytest -v --alluredir=allure-results 

      - name: Get Allure history
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: allure-history
        continue-on-error: true

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_branch: gh-pages
          publish_dir: allure-report